services:
  db:
    image: postgres
    container_name: players_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lelio
      POSTGRES_PASSWORD: Oilel2025+
      POSTGRES_DB: calcio
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: lpjr03@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Oilel2025+
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  backend:
    driver: bridge