name: Docker Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: your-dockerhub-user/your-image

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ github.ref == 'refs/heads/main' && 'your-dockerhub-user/your-image:latest' || '' }}
            ${{ startsWith(github.ref, 'refs/tags/v') && 'your-dockerhub-user/your-image:${{ github.ref_name }}' || '' }}
            ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v') && format('your-dockerhub-user/your-image:{0}', github.run_id) || '' }}
          labels: ${{ steps.meta.outputs.labels }}
